[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Lokaltog/vim-powerline'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'leafgarland/typescript-vim'
